apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  MONGO_DATABASE: mongodb
  MONGO_USERNAME: mongodbadmin
  MONGO_PASSWORD: admin123
  MONGO_HOST: mongodb-service