apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: customer-ingress
 annotations:
  ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
  - host: mastercloudapps.com
    http:
      paths:    
      - path: /iss-policy-service
        backend:
          serviceName: iss-api-gateway
          servicePort: 8085
      - path: /iss-policy-search-service
        backend:
          serviceName: iss-api-gateway
          servicePort: 8085
      - path: /iss-product-service
        backend:
          serviceName: iss-api-gateway
          servicePort: 8085
      - path: /iss-payment-service
        backend:
          serviceName: iss-api-gateway
          servicePort: 8085