apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  database-name: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  database-password: UGlvdF8xMjM=
  database-user: cGlvdHI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iss-product-service
  labels:
    app: iss-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iss-product-service
  template:
    metadata:
      labels:
        app: iss-product-service
    spec:
      containers:
      - name: iss-product-service
        image: fpoirier2020/iss-product-service
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: iss-product-service
  labels:
    app: iss-product-service
    spring-boot: "true"
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: iss-product-service