version: '3'

services:      
  iss-api-gateway:
    container_name: iss-api-gateway
    image: iss-api-gateway
    build:
      context: ../
      dockerfile: ./docker/Dockerfile    
    ports:
      - "8085:8085"
    environment:
      - "SPRING_PROFILES_ACTIVE=test"
